- name: Install core packages
  ansible.builtin.package:
    name:
      - cargo
      - emacs
      - firefox
      - g++
      - gcc
      - gdb
      - htop
      - nodejs
      - npm
      - pipewire-audio
      - wget
  tags: packages
