- name: Install core packages
  ansible.builtin.package:
    name:
      - cargo
      - emacs
      - firefox
      - g++
      - gcc
      - gdb
      - htop
      - nodejs
      - npm
      - pipewire-audio
      - wget
  tags: packages

# -------- Snap packages --------
- name: Install packages using Snap
  community.general.snap:
    name:
      - obsidian
    classic: true
  tags: packages

# -------- Rust packages --------
- name: Install Rust packages
  community.general.cargo:
    name:
      - ripgrep
      - zellij
  tags: packages

# -------- Claude Code -------
- name: Check if Claude Code is installed
  become: false
  ansible.builtin.stat:
    path: "~/.local/bin/claude"
  register: ret
  tags: packages

- name: Install Claude Code using the native installer
  become: false
  ansible.builtin.shell: curl -fsSL https://claude.ai/install.sh | bash
  when: not ret.stat.exists
  tags: packages
